### PR TITLE
switch to python3 namespace package

### PR DESCRIPTION
**Pull request by dcfidalgo**
@frascuchon This is the change we talked about yesterday.

### CODE REVIEW

**Comment by frascuchon** [comment]
Just to be sure. We need all namespaced modules configured in this way if we install from a package distribution wheel??

I mean, if we merge this change and without change the rest of the packages (biome-data, biome-classifier, extraction...) Will we break the package ecosystem installation?

**Comment by dcfidalgo** [comment]
No, following [these docs](https://packaging.python.org/guides/packaging-namespace-packages/) the two ways are compatible:
- native python 3 namespace packages, that is without any init file in the namespace package
- pkgutil-style namespace packages, that is an init file that contains **only** 
`__path__ = __import__('pkgutil').extend_path(__path__, __name__)`

What will break, is the autocomplete function for Pycharm, somehow it can not handle both cases at the same time.

**Comment by dcfidalgo** [comment]
@frascuchon can we merge this PR and the similar ones in biome-data and biome-classifier?

**Comment by frascuchon** [comment]
> @frascuchon can we merge this PR and the similar ones in biome-data and biome-classifier?

We will start merging biome-data and see the changes in dev. If everything if fine, then we can start merge the other ones

**Pull request merged**
